---
# tasks file for setup_computer

# Set shell configuration path globally for all tasks

- name: Install packages
  include_tasks: install_packages_{{ansible_os_family}}.yml

- include_tasks: install_uv.yml

- include_tasks: install_ruff.yml
