#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/golang

go_version: "1.25.6"
go_archive: "go{{ go_version }}.linux-amd64.tar.gz"
go_url: "https://go.dev/dl/{{ go_archive }}"
go_install_dir: "/usr/local"
go_bin_path: "/usr/local/go/bin/go"
