- name: Install packages
  become: true
  apt:
    name:
      # Clipboard
      - wl-clipboard
      # Java
      - jdk21-openjdk
      # Build tools
      - base-devel
      - cmake
      # Development tools
      - git
      - htop
      - wget
      - curl
      - ripgrep
      - libtool
      - unzip

      # Programming language
      - nodejs
      - npm

      - clang
    state: present
    update_cache: yes
