---
# tasks file for setup_computer

# Set shell configuration path globally for all tasks

- name: Install packages
  include_tasks: install_packages_{{ansible_os_family}}.yml
  tags: [ setup_computer ]
  
